### ISSUE TITLE
Volumetric terrain

### ISSUE THREAD

**Issue by bfops** [bfops/playform#117]
Store/generate/modify terrain with volumetric data structures (something voxel-ish).

  * [x] Sparse Voxel Octree (86962f8a9d6c94446d8ecb877db4fb426296aa90)
    * [x] `1/2^n` width voxels (1b0f866f63d5ea7a8d84b4ea187b87a663b19d65).
  * [x] Isosurface extraction (generate a mesh from the SVO) (86962f8a9d6c94446d8ecb877db4fb426296aa90).
    * [x] Extract normals (eb90943d155c37185043970069d86faf4985130c).
  * [ ] Collision detection between `Aabb3`s and SVO (https://github.com/bfops/playform/issues/120).
  * [ ] Voxels of different materials (https://github.com/bfops/playform/issues/121).
    * [ ] Voxel trees (https://github.com/bfops/playform/issues/122).
  * [ ] Represent the same space at several LODs (relevant: https://github.com/bfops/bit-svo/issues/2).
  * [x] Voxel terrain generation (generate SVO data from the heightmap) (2a3c4f9de961eda6df28ecd866a186d3f4a3eee9).
  * [x] Terrain texturing ([this](http://http.developer.nvidia.com/GPUGems3/gpugems3_ch01.html) might be useful) (20994f2479e4ca6da54805741148b2f897547011).

**Comment by bfops** [comment]
Based on [this article](http://procworld.blogspot.ca/2010/11/from-voxels-to-polygons.html) and some thinking, I'm thinking we treat everything as a contiguous volum. We store a sparse voxel octree, where is either entirely inside or entirely outside the volume, or it contains a single surface vertex and a record of where the surface intersects the edges. If the surface intersects an edge, all the cubes adjacent to that edge (four of them) intersect the surface, too, so we generate four triangles using the four cubes' vertices and the intersection point of the edge.

**Comment by bfops** [comment]
WIP on the [voxel branch](https://github.com/bfops/playform/tree/voxel).

**Comment by bfops** [comment]
Moving the pre-volumetric terrain to the pre-svo branch, merging the voxel branch into master, and moving leftover list items into separate issues.
